"""empty message

Revision ID: 44a84e179485
Revises: e4abb9581242
Create Date: 2024-10-20 16:52:00.002048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a84e179485'
down_revision = 'e4abb9581242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('IPAddr', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=180), nullable=True),
    sa.Column('reported', sa.DateTime(), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ip_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ip_report_IPAddr'), ['IPAddr'], unique=False)
        batch_op.create_index(batch_op.f('ix_ip_report_source'), ['source'], unique=False)

    with op.batch_alter_table('bad_ip_report', schema=None) as batch_op:
        batch_op.drop_index('ix_bad_ip_report_badIP')
        batch_op.drop_index('ix_bad_ip_report_source')

    op.drop_table('bad_ip_report')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bad_ip_report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=20), nullable=True),
    sa.Column('badIP', sa.VARCHAR(length=20), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=180), nullable=True),
    sa.Column('reported', sa.DATETIME(), nullable=True),
    sa.Column('expires', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bad_ip_report', schema=None) as batch_op:
        batch_op.create_index('ix_bad_ip_report_source', ['source'], unique=False)
        batch_op.create_index('ix_bad_ip_report_badIP', ['badIP'], unique=False)

    with op.batch_alter_table('ip_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ip_report_source'))
        batch_op.drop_index(batch_op.f('ix_ip_report_IPAddr'))

    op.drop_table('ip_report')
    # ### end Alembic commands ###
