"""Update to token table

Revision ID: f21a3cc46a1e
Revises: f9c92666beeb
Create Date: 2019-01-09 14:50:15.719275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21a3cc46a1e'
down_revision = 'f9c92666beeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_token', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_token', 'notes')
    # ### end Alembic commands ###
