"""Initial structure

Revision ID: f9c92666beeb
Revises: 
Create Date: 2018-12-17 21:10:06.737322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c92666beeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipAddr', sa.String(length=20), nullable=True),
    sa.Column('validFrom', sa.DateTime(), nullable=True),
    sa.Column('validTo', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('lastUsed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_token_token'), 'access_token', ['token'], unique=False)
    op.create_table('bad_ip_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('badIP', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=180), nullable=True),
    sa.Column('reported', sa.DateTime(), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bad_ip_report_badIP'), 'bad_ip_report', ['badIP'], unique=False)
    op.create_index(op.f('ix_bad_ip_report_source'), 'bad_ip_report', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bad_ip_report_source'), table_name='bad_ip_report')
    op.drop_index(op.f('ix_bad_ip_report_badIP'), table_name='bad_ip_report')
    op.drop_table('bad_ip_report')
    op.drop_index(op.f('ix_access_token_token'), table_name='access_token')
    op.drop_table('access_token')
    # ### end Alembic commands ###
